### ISSUE TITLE
Option to Pause reporting status of other telescopes

### ISSUE THREAD

**Issue by majkelx** [astromg/TOI#10]
On running instance of TOI generates constant trafic on all telescopes:
```
PUT /api/v1/telescope/0/commandstring
GET /api/v1/camera/0/ccdtemperature
GET /api/v1/camera/0/cooleron
GET /api/v1/camera/0/setccdtemperature
GET /api/v1/dome/0/slewing
GET /api/v1/camera/0/camerastate
GET /api/v1/telescope/0/tracking
GET /api/v1/telescope/0/slewing
GET /api/v1/dome/0/shutterstatus
GET /api/v1/filterwheel/0/position
```

When bug tracing, or on maintaenance, it makes impossible to follow the logs of those instrument, and make tests of their API.

It would be good to have potion to pause updates for specific instrument, or run TOI in the mode in which it does not raport other instruments state.

**Comment by astromg** [comment]
I assume it would be best to have a pushbutton that stops subscription. 

> self.dome = self.observatory_model.get_telescope(tel).get_dome()
> self.add_background_task(self.dome.asubscribe_slewing(self.domeStatus_update))
> await self.run_background_tasks()

can I use this method to stop subscription? Can anyone advise how to use it?

> def unsubscribe(self, cq):
>     del self._subscribers[self._subscribers.index(cq)]
>     cq.stop()

@MMiirrkk advised solution below. Will it work? 

> self.dome = self.observatory_model.get_telescope(tel).get_dome()
> self.cq = await self.dome.asubscribe_slewing(self.domeStatus_update)
> self.add_background_task()
> await self.run_background_tasks()
>
> def on_stop_pushbutton:
>    self.cq.stop()

@ernestworkspace

**Comment by ernestworkspace** [comment]
Better use `await cq.stop_and_wait()` instead `cq.stop()` if you can stop in async method

**Comment by ernestworkspace** [comment]
Better use `await cq.stop_and_wait()` instead `cq.stop()` if you can stop in async method

**Comment by ernestworkspace** [comment]
co do reszty pytania to `self.dome.asubscribe_slewing(self.domeStatus_update)` wsadzanie do tasków chyba nie jest potrzebne. Zapamiętywać CQ gdzieś trzeba ale to robi API z tego co widzę więc nie musisz przypisywać wyniku `self.cq = ...`
