### ISSUE TITLE
TOI hangs on Open Plan Dialog on Ubuntu

### ISSUE THREAD

**Issue by majkelx** [astromg/TOI#11]
The problem is seriuos right now on the `aux` and `nadir`:
If you click `Load Plan`, the TOI freezes. If you wait for like minute The OpenFile window finally apperars, but its not clickable or cancelable, and you have to kill an App.

The problem does not apear before you select the telescope. Afer selecting the telescope it's unavoidable.

We tried to change the `parent` parametr of the Window from `self` to `None`. It helped for a while but then it's like it was idependent of the value of the `parent` parameter. 

It's somehow connected to the mess in the windows tree structure in Qt or Ubuntu, after changes made by telescope selection. 

The problem is independent of the branch, is the same in `main` and in the `TOI_development`

We tried to comment out some of the features which generates errors:
* waether tab
* 2.5m telescope monitoring
without success.

There are still a lot warnings and stack-traces in the output on TOI. But hard to say if the are related somehow to the problem.

Thats all we know. The only clue is that it not happen before telescope selection and alway after.

**Comment by gerhajdu** [comment]
Comment: TOI also uses 100% of one processor core when doing absolutely nothing. Disabling the weather tab decreased the processor usage when doing nothing to about 60%.

Still, the only way to load a plan now is to open TOI, load the plan, and then click and take control over the telescope. If the order is reversed, the load plan window becomes very unresponsive.

**Comment by astromg** [comment]
Version for testing purpose ready to pull from development_TOI branch

**Comment by WojtekPych** [comment]
2023-05-26
The plan is loading without any problems.

However there is a minor bug in running the plan. Let's take an example plan:

ZERO seq=11/u/0
DARK seq=1/u/1800
DARK seq=1/u/1800
ZERO seq=11/u/0

The program will make: 1 zero, 1 dark, 1 dark, 11 zeros.
Wojtek

**Comment by astromg** [comment]
Issue closed, while not resolved and till now not encountered any time more.
