### ISSUE TITLE
Observer Tab and/or in the Observing Plan

### ISSUE THREAD

**Issue by WojtekPych** [astromg/TOI#13]
We need to let the observers write their names into the headers. For this purpose we propose to make a new tab. It might be dark gray when it is empty.
Alternatively or in parallel observer name could be set in the observing plan.

**Comment by majkelx** [comment]
I would suggest red when empty and exposure impossible. 

There is a number of task to be done before observational and setting the observer should be one of those. 

To make observers life easier, there can be combobox with previously entered values. So during subsequent nights observers just have to select first position.

**Comment by WojtekPych** [comment]
It would be better to let the exposure be possible without the names.

**Comment by astromg** [comment]
Observer QEditbox is ready, waiting for ocaboxapi.
