### ISSUE TITLE
ZB08 cannot stop tracking

### ISSUE THREAD

**Issue by WojtekPych** [astromg/TOI#17]
2023-05-26 07:30
Cannot stop tracking of the telescope. I have tried to switch this a number of times and the mount does not react.

BTW. After slewing the telescope to selected AZ and ALT the tracking should be implicitly OFF.

**Comment by WojtekPych** [comment]
Temporary solution - go to rdesktop on TCU and use ASA autoslew to stop tracking.

**Comment by astromg** [comment]
not encountered (reported) any time more. Assumed as curiosity.
