### ISSUE TITLE
Plan Manager weirdness

### ISSUE THREAD

**Issue by gerhajdu** [astromg/TOI#18]
The Plan Manager doesn't load the correct number of requested exposures in a sequence when the number of requested exposures per band is different. For example, requesting the following:
seq=1/u/240,2/g/8,2/r/5
seq=1/u/240,2/g/8,2/r/5
...
results in only u-band images being taken.
Also, writing something like this to get around this issue:
seq=2/g/8
seq=2/r/5
seq=1/u/240
...
results in only 1 u, g, r image taken by request.

**Comment by astromg** [comment]
The issue with jumping to the next object is fixed. The fix for one-line sequences issue is in the development

**Comment by astromg** [comment]
fixed
