### ISSUE TITLE
Basic information in the Aux Monitor Window

### ISSUE THREAD

**Issue by WojtekPych** [astromg/TOI#19]
The information is incorrect.

![screenshot2023-05-30T03-32-45](https://github.com/astromg/TOI/assets/96439508/2ebb9058-23d9-469d-9420-4b9b32abda38)

Correct information:
min= 306     max= 64571
mean= 403  rms= 623  sigma= 8
fwhm= 3.4

**Comment by WojtekPych** [comment]
Why can't I add assignees and labels?

**Comment by WojtekPych** [comment]
There is too much information for quick look at the quality.
It should be just:

mode      fwhm
359         3.4

**Comment by WojtekPych** [comment]
The image is completely invisible because of white circles.

**Comment by WojtekPych** [comment]
The file is here: aux:/home/observer/Desktop/fits_zb08/0094/zb08c_0094_81308.fits
The information is incorrect on most (maybe all) of the files.

**Comment by astromg** [comment]
ok, I identified the bug. I will fix the toi version and add option to display or not stars in the FITS window tomorrow.

**Comment by astromg** [comment]
fixed
