### ISSUE TITLE
Telescope fans vs dome fans - make distinction and include both

### ISSUE THREAD

**Issue by pkarczmarek** [astromg/TOI#22]
There are two different types of fans: the fans at the telescope (just above the mirror) and the fans in the dome.

Fans at the telescope are turned on in Alpaca program (red window), while the fans in the dome are turned on in the ASA Dome program.

In TOI, when a slider next to VENTILATORS turns on/off the fans, these are actually the telescope fans, although the slider is located in the "dome" section of the window.

I suggest:
- [ ] to rename the fan slider to "telescope fans" and to remove it from the dome section of the window
- [ ] to introduce a slider "dome fans" into the dome section.

**Comment by astromg** [comment]
done, just waiting for dome fans to work
