### ISSUE TITLE
Exposures don't finish automatically and have to be retaken with a "resume" button

### ISSUE THREAD

**Issue by pkarczmarek** [astromg/TOI#23]
It might be an old bug, maybe already resolved? When I observed in April 2023, several times (1/4 or 1/3 of all observations) an exposure would start after a START button (in Instrument Manual Control window) was clicked, but would not finish automatically. The program seemed to "forget" that it was taking an exposure and had to be "poked" with a "Resume" button (in Plan Manager window) to be reminded and start taking it over again. After pressing the "Resume" button the exposure restarted and was saved as normal. 

Can @ocacontrolroom check if this problem still appears?

**Comment by astromg** [comment]
known issue, originating via ocaboxapi and tic by alpaca. Highly trained specialist are working on effective but pretty workaround.
