### ISSUE TITLE
Wrong calculation of RA from degrees

### ISSUE THREAD

**Issue by pkarczmarek** [astromg/TOI#24]
I typed RA=200 to the RA field in the Mount Manual Control window. The program interpreted this value as about 116.

![IMG_20230427_202945](https://github.com/astromg/TOI/assets/97190280/f173573d-78af-49b5-8cb0-d52d947cd8d9)

**Comment by astromg** [comment]
Fixed - Ra, Dec, Alt and Az values are now checked. BTW - funny, it just interpreted this as h angle with multiple rotation.
