### ISSUE TITLE
TOI crashes after load plan without control

### ISSUE THREAD

**Issue by ocacontrolroom** [astromg/TOI#31]
After starting TOI, if the first action is to load plan (and not to take control), the program crashes with the error message:
```
Traceback (most recent call last):
  File "/home/observer/src/TOI/plan_gui.py", line 533, in loadPlan
    self.update_table()          
  File "/home/observer/src/TOI/plan_gui.py", line 122, in update_table
    self.update_plan()
  File "/home/observer/src/TOI/plan_gui.py", line 116, in update_plan
    slotTime = slotTime + (float(x_seq.split("/")[0]) * (float(x_seq.split("/")[2]) + float(self.parent.overhed)))
AttributeError: 'TOI' object has no attribute 'overhed'
Aborted (core dumped)
```
This behavior doesn't happen if TOI already had control but doesn't have anymore, it only happens if TOI never had control.

I suggest to add a window prompt "You don't have control" that pops up instead of TOI crashing.

**Comment by astromg** [comment]
Probably the issue was not taking control, but rather that no telescope was selected. Fixed in next update.
