### ISSUE TITLE
TOI ends whole automatic skyflat routine when it's too bright in one filter

### ISSUE THREAD

**Issue by ocacontrolroom** [astromg/TOI#32]
When executing automatic skyflat routine, e.g. `7/g/a,7/i/a,7/u/a` in the morning, what happened was that it was already too bright to do flats in the i band, so the automatic routine ended. However, it was still dark enough for the u-band flats. 

I would expect the routine to give up on an individual filter when it's too bright (or too dark during evening flats) and proceed to the next filter. Instead, I noticed the routine ended, and I ran only `7/u/a`, which successfully did skyflats in the u band.

@MMiirrkk

**Comment by MMiirrkk** [comment]
For now just put in separate line
